/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.*;
import javax.swing.JOptionPane;
/**
 *
 * @author diego
 */
public class VistaCalculadora extends javax.swing.JFrame {
    private ControladorCalculadora controlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCalculadora.class.getName());

    public void setControlador(ControladorCalculadora controlador) {
        this.controlador = controlador;
    }
public void mostrarMensajeExito(String mensaje) {
    JOptionPane.showMessageDialog(
        null,                  
        mensaje,              
        "Éxito",               
        JOptionPane.INFORMATION_MESSAGE 
    );
}
    public void mostrarMensajeError(String mensaje) {
    JOptionPane.showMessageDialog(
        null,                
        mensaje,             
        "Error",             
        JOptionPane.ERROR_MESSAGE 
    );
    }
    private void limpiar(){
        txtCodigo.setText("");
        txtNombre.setText("");
    }
    /**
     * Creates new form VistaCalduladora
     */
    public VistaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnModificarVendedor = new javax.swing.JButton();
        btnModificarVendedor1 = new javax.swing.JButton();
        btnModificarVendedor2 = new javax.swing.JButton();
        btnModificarVendedor3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CALCULADORA");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Numero A");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Numero B");

        btnModificarVendedor.setBackground(new java.awt.Color(242, 242, 242));
        btnModificarVendedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarVendedor.setText("RESTAR");
        btnModificarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVendedorActionPerformed(evt);
            }
        });

        btnModificarVendedor1.setBackground(new java.awt.Color(242, 242, 242));
        btnModificarVendedor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarVendedor1.setText("MULTIPLICAR");
        btnModificarVendedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVendedor1ActionPerformed(evt);
            }
        });

        btnModificarVendedor2.setBackground(new java.awt.Color(242, 242, 242));
        btnModificarVendedor2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarVendedor2.setText("SUMAR");
        btnModificarVendedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVendedor2ActionPerformed(evt);
            }
        });

        btnModificarVendedor3.setBackground(new java.awt.Color(242, 242, 242));
        btnModificarVendedor3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificarVendedor3.setText("DIVIDIR");
        btnModificarVendedor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVendedor3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtCodigo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarVendedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarVendedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificarVendedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarVendedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarVendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarVendedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVendedorActionPerformed
     if(txtCodigo.getText().trim().isEmpty()){
            mostrarMensajeError("Llena el valor A");
            return;
        }
        
        if(txtNombre.getText().trim().isEmpty()){
            mostrarMensajeError("Llena el valor B");
            return;
        }
        
        double a = Double.parseDouble(txtCodigo.getText());
        double b = Double.parseDouble(txtNombre.getText());
        
        
        mostrarMensajeExito(controlador.getUsuario()+ " realizo una resta. La respuesta es: " + controlador.restar(a, b));
        limpiar();
    }//GEN-LAST:event_btnModificarVendedorActionPerformed

    private void btnModificarVendedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVendedor1ActionPerformed
        if(txtCodigo.getText().trim().isEmpty()){
            mostrarMensajeError("Llena el valor A");
            return;
        }
        
        if(txtNombre.getText().trim().isEmpty()){
            mostrarMensajeError("Llena el valor B");
            return;
        }
        
        double a = Double.parseDouble(txtCodigo.getText());
        double b = Double.parseDouble(txtNombre.getText());
        
        
        mostrarMensajeExito(controlador.getUsuario()+ " realizo una multiplicacion. La respuesta es: " + controlador.multiplicar(a, b));
        limpiar();
    }//GEN-LAST:event_btnModificarVendedor1ActionPerformed

    private void btnModificarVendedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVendedor2ActionPerformed
        if(txtCodigo.getText().trim().isEmpty()){
            mostrarMensajeError("Llena el valor A");
            return;
        }
        
        if(txtNombre.getText().trim().isEmpty()){
            mostrarMensajeError("Llena el valor B");
            return;
        }
        
        double a = Double.parseDouble(txtCodigo.getText());
        double b = Double.parseDouble(txtNombre.getText());
        
        
        mostrarMensajeExito(controlador.getUsuario()+ " realizo una suma. La respuesta es: " + controlador.sumar(a, b));
        limpiar();

    }//GEN-LAST:event_btnModificarVendedor2ActionPerformed

    private void btnModificarVendedor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVendedor3ActionPerformed
       if(txtCodigo.getText().trim().isEmpty()){
            mostrarMensajeError("Llena el valor A");
            return;
        }
        
        if(txtNombre.getText().trim().isEmpty()){
            mostrarMensajeError("Llena el valor B");
            return;
        }
        
        double a = Double.parseDouble(txtCodigo.getText());
        double b = Double.parseDouble(txtNombre.getText());
        
        if(b == 0){
            mostrarMensajeError("B no puede ser 0");
            return;
        }
        
        mostrarMensajeExito(controlador.getUsuario()+ " realizo una division. La respuesta es: " + controlador.dividir(a, b));
        limpiar();
    }//GEN-LAST:event_btnModificarVendedor3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaCalculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarVendedor;
    private javax.swing.JButton btnModificarVendedor1;
    private javax.swing.JButton btnModificarVendedor2;
    private javax.swing.JButton btnModificarVendedor3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
